script web

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,11 +1,25 @@
+#!/bin/bash
 
-#!/usr/bin/env bash
-# Write a Bash script that transfers a file from our client to a server
-if [[ $# -lt 3 ]];
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY" >&2
-    exit 2
+# Check if the number of arguments is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assigning the parameters to variables
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY_PATH=$4
+
+# Use scp to transfer the file to the server's user home directory
+scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
+
+# Check if the scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully."
 else
-     scp -i "$4" -o "StrictHostKeyChecking no" "$1" "$3"@"$2":~/
+    echo "File transfer failed."
+    exit 1
 fi
 
